### ISSUE TITLE
Copyright Problems

### ISSUE THREAD

**Issue by valoeghese** [fatlard1993/bamboo-spikes#1]
The mod should be relicenced under `GPL` due to using assets from https://github.com/vini2003/bamboo-tweaks

**Comment by vini2003** [comment]
As the owner of BambooTweaks, I find this disrespectful, and it is not your first offense. You are making use of my work, claiming it as yours, and likely attempting to profit over it in CurseForge.

If you continue to do so, I may take further action.

**Comment by fatlard1993** [comment]
Woah, woah.. First off let me apologize for my ignorance.. I meant no disrespect in any of this. I'm still brand new to both the mod world and the myriad of licences. I am in this for fun and make no money on any of this at all.. 

(This mod and these 2: https://github.com/fatlard1993/bamboo-fence and https://github.com/fatlard1993/bamboo-block) are all based on your mod BambooTweaks. I simply picked your mod because I liked it and wanted to tear it apart and learn how it works.. Its how I learn best.. I very much appreciate your work I simply don't yet fully understand the educate. Please enlighten me instead of scald me.

I will of course change whatever you would like.

**Comment by vini2003** [comment]
I am sorry for being so stern on you right away. Usually, when this happens, it is not with good intentions, so I was expecting that right away.

If you are indeed using it for learning, I'd like to request you to at least change the assets. You have two options, after all - licensing this as GPLv3 so you can keep my assets, or MIT with your own assets. I don't intend on being an asshole to someone with good intentions, thus I am sorry for having been one earlier, since I had no clue what your motivation was.

I guess that's cleared up now. Just be more careful with this in the future and try to make your own assets, otherwise, even if perfectly legal, people can still take what you're doing negatively - even if your intentions are solely learning.

Anyway, that wraps it up - have as nice of a day as you can in this quarantine!

**Comment by vini2003** [comment]
You may realize I edited that message, and it is because the legality of GPLv3 mods in itself is rather questionable, so I don't feel like dying on that hill very much.

**Comment by vini2003** [comment]
@fatlard1993 I have released a new Bamboo Tweaks version with your additions. Thank you for the PRs!

![](https://i.imgur.com/1vvzwNo.png)

**Comment by fatlard1993** [comment]
Thanks for being understanding. I would like to keep your assets as I am still garbage at that right now but the license still confuses me a bit. I have updated my license for these 3 projects on GH and CF to match yours. But is there anything else I need to do, or that you would like me to do?

**Comment by vini2003** [comment]
Legally everything's fine now, so that's not a worry. Consider swapping the assets in the future when you feel you're more used to it; but for now it's perfectly fine.

**Comment by fatlard1993** [comment]
Thank you!
